# syntax=docker/dockerfile:1
FROM ubi8/python-311

LABEL org.opencontainers.image.version=0.1
LABEL org.opencontainers.image.title="jobs autoscaler demo - API app"
LABEL org.opencontainers.image.description="Demo app - module 1/3 that contains API to write into tasks queue"


# DEBUG ONLY: the next block is required for dev/debug activities only and should be left commented by default
# USER root
# RUN yum -y install net-tools iputils
# USER 10001


# BUILD: section with commands to build the app
COPY python-app/requirements.txt /home/
RUN pip install -r /home/requirements.txt
COPY python-app/scripts/*.py /home/app/


# RUN: section that defines the app to be run
WORKDIR /home/app/
CMD ["python3", "tasks-api.py"]
