apiVersion: v1
kind: Service
metadata:
  name: {{ include "apichart.fullname" . }}-svc
  labels:
    {{- include "apichart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "apichart.selectorLabels" . | nindent 4 }}
