# Default values for jobschart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


appSettings:
  # Define the workers shared data storage size
  appdataStorage: 10Gi
  # Define whether to use pre-created storage volumes managed by the cluster admin
  # This is useful when using underlying storage shared across different projects
  # Valid values are ' true | false '
  # Deault is ' false' 
  useStaticAppdataVolume: False
  # Define the name of a pre-provisoned volume
  # The system administrator must expose the PV to the namespace
  staticAppdataVolumeName: appdata-pv
  # Define the container registry credentials in .dockerconfigjson and base64 encoded
  registryCredentials: 


apichart:
  enabled: True
  appSettings:
    debug: True
    useAPIToken: True
    apiTokenValue: OTZ3OUVYZmVuMnpFSnhjZA==
  image:
    # Update to reflect relevant repository
    repository: docker.io/azenhab/jobs-api   
    tag: latest
    pullPolicy: Always
  queueService:
    svcName: queue-svc
    port: 6379
  route:
    # Specifies whether the API is to be accesible from outside the project and cluster
    enabled: true


queuechart:
  enabled: True
  appSettings:
    debug: True
    queuePassword: 
  image:
    # Update to reflect relevant repository
    repository: registry.redhat.io/rhel9/redis-7 
    tag: latest
    pullPolicy: IfNotPresent
  queueService:
    svcName: queue-svc
    port: 6379


workerchart:
  enabled: True
  appSettings:
    debug: True
  image:
    # Update to reflect relevant repository
    repository: docker.io/azenhab/jobs-worker
    tag: latest
    pullPolicy: Always
  queueService:
    svcName: queue-svc
    port: 6379



