apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-queue-pvc
  labels: 
    {{- include "queuechart.labels" . | nindent 4 }}
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.appSettings.queueStorage }}
