apiVersion: v1
kind: ConfigMap
metadata:
   name: my-configmap
data:
   APP_DEBUG: "True"
   API_TOKEN: "True"
   API_TOKEN_VALUE: "96w9EXfen2zEJxcd"
   REDIS_URL: "redis-svc"
   REDIS_PORT: "6379"
   REDIS_PWD: "3R8P8reeQVqTrwGT"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
data:
  REDIS_PASSWORD: M1I4UDhyZWVRVnFUcndHVA==    # REMINDER redis password base64 encoded
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: my-dockerio-secret
type: docker-registry
data:
  .dockerconfigjson: e2F1dGhzOiB7ZG9ja2VyLmlvOiB7dXNlcm5hbWU6IDx1c2VybmFtZT4sIHBhc3N3b3JkOiA8cGFzc3dvcmQ+fX19 # REMINDER docker registry connection base64 encoded
