# syntax=docker/dockerfile:1
## Builder container specification - base image with c++ compiler
FROM ubi8 as builder

USER root
RUN yum -y install gcc gcc-c++ make && mkdir -p /home/app/src /home/app/bin



## Builder container specification - used to compile cpp code
FROM builder as compiler

COPY ./cpp-app /home/app
RUN (cd /home/app/ && make)



## Final application container specification
FROM ubi8/python-311

LABEL org.opencontainers.image.version=0.1
LABEL org.opencontainers.image.title="OCP jobs demo - worker app"
LABEL org.opencontainers.image.description="Demo job app - part 3/3 that contains python and cpp apps to run as OCP jobs"


# DEBUG ONLY: the next block is required for dev/debug activities only and should be removed
# USER root
# RUN yum -y install net-tools iputils
# USER 10001


# BUILD: section with commands to build the app
RUN pip install redis
COPY --from=compiler /home/app/bin/calculator /home/app/ 
COPY python-app/src/*.py /home/app/


# RUN: section that defines the app to be run
WORKDIR /home/app/
CMD ["python3", "worker.py"]

