apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  labels:
    {{- include "jobschart.labels" . | nindent 4 }}
data:
  API_TOKEN_VALUE: {{ .Values.apichart.appSettings.apiTokenValue }} 
type: Opaque


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-queue-secret
  labels:
    {{- include "jobschart.labels" . | nindent 4 }}
data:
  REDIS_PASSWORD: {{ .Values.queuechart.appSettings.queuePassword }} 
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  labels:
    {{- include "jobschart.labels" . | nindent 4 }}
type: docker-registry
data:
  .dockerconfigjson: {{ .Values.appSettings.registryCredentials }} 

