apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-appdata-pvc
  labels: 
    {{- include "jobschart.labels" . | nindent 4 }}
spec:
  storageClassName: aws-efs
{{- if .Values.appSettings.useStaticAppdataVolume}}
  volumeName: {{ .Values.appSettings.staticAppdataVolumeName }} 
{{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appSettings.appdataStorage }} 
