apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-appdata-pvc
  labels: 
    {{- include "jobschart.labels" . | nindent 4 }}
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 
